# Generated by Django 4.0.5 on 2022-07-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_genre_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='world_premiere',
        ),
        migrations.AddField(
            model_name='movie',
            name='kinopoisk_id',
            field=models.IntegerField(default=0, verbose_name='Кинопоиск'),
        ),
    ]
